### ISSUE TITLE
Cant save lesson

### ISSUE THREAD

**Issue by mnguyen081002** [mnguyen081002/codesmooth-api#1]
table: 'lessons',
column: undefined,
dataType: undefined,
constraint: 'PK_9b9a8d455cac672d262d7275730',
file: 'nbtinsert.c',
line: '664',
routine: '_bt_check_unique'
}
query: ROLLBACK
[Nest] 30  - 05/13/2023, 12:24:50 PM   ERROR [ExceptionsHandler] duplicate key value violates unique constraint "PK_9b9a8d455cac672d262d7275730"
QueryFailedError: duplicate key value violates unique constraint "PK_9b9a8d455cac672d262d7275730"
at PostgresQueryRunner.query (/app/src/driver/postgres/PostgresQueryRunner.ts:299:19)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at InsertQueryBuilder.execute (/app/src/query-builder/InsertQueryBuilder.ts:163:33)
at SubjectExecutor.executeInsertOperations (/app/src/persistence/SubjectExecutor.ts:428:42)
at SubjectExecutor.execute (/app/src/persistence/SubjectExecutor.ts:137:9)
at EntityPersistExecutor.execute (/app/src/persistence/EntityPersistExecutor.ts:194:21)
at LessonService.saveLesson (/app/src/modules/admin/lesson/lesson.service.ts:18:5)
at LessonController.saveLesson (/app/src/modules/admin/lesson/lesson.controller.ts:17:17)
[Nest] 30  - 05/13/2023, 12:24:50 PM   ERROR [HTTPLogger] Request: {POST /api/admin/lesson 500 - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 ::ffff:192.168.0.4 Response: { undefined 2210ms }
QueryFailedError: duplicate key value violates unique constraint "PK_9b9a8d455cac672d262d7275730"
at PostgresQueryRunner.query (/app/src/driver/postgres/PostgresQueryRunner.ts:299:19)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at InsertQueryBuilder.execute (/app/src/query-builder/InsertQueryBuilder.ts:163:33)
at SubjectExecutor.executeInsertOperations (/app/src/persistence/SubjectExecutor.ts:428:42)
at SubjectExecutor.execute (/app/src/persistence/SubjectExecutor.ts:137:9)
at EntityPersistExecutor.execute (/app/src/persistence/EntityPersistExecutor.ts:194:21)
at LessonService.saveLesson (/app/src/modules/admin/lesson/lesson.service.ts:18:5)
at LessonController.saveLesson (/app/src/modules/admin/lesson/lesson.controller.ts:17:17)
query: SELECT "LessonEntity"."id" AS "LessonEntity_id", "LessonEntity"."created_at" AS "LessonEntity_created_at", "LessonEntity"."updated_at" AS "LessonEntity_updated_at", "LessonEntity"."deleted_at" AS "LessonEntity_deleted_at", "LessonEntity"."title" AS "LessonEntity_title", "LessonEntity"."isCompleted" AS "LessonEntity_isCompleted", "LessonEntity"."order" AS "LessonEntity_order", "LessonEntity"."components" AS "LessonEntity_components", "LessonEntity"."summary" AS "LessonEntity_summary", "LessonEntity"."course_category_id" AS "LessonEntity_course_category_id" FROM "lessons" "LessonEntity" WHERE "LessonEntity"."id" IN ($1) -- PARAMETERS: [589880434686375300]
query: START TRANSACTION
query: INSERT INTO "lessons"("id", "created_at", "updated_at", "deleted_at", "title", "isCompleted", "order", "components", "summary", "course_category_id") VALUES ($1, DEFAULT, DEFAULT, DEFAULT, $2, DEFAULT, DEFAULT, $3, $4, $5) RETURNING "created_at", "updated_at", "isCompleted", "order", "summary" -- PARAMETERS: [589880434686375300,"Cách cài đặt môi trường NodeJS","[{\"type\":\"Text\",\"content\":{\"html\":\"<h2>Giới thiệu về NodeJS</h2>\"}},{\"type\":\"Text\",\"content\":{\"html\":\"<h2>NodeJS là một môi trường phát triển lập trình, dựa trên chrome V8 và các lib của C++</h2>\"}},{\"type\":\"Text\",\"content\":{\"html\":\"<h3>ccccccccccccc</h3>\"}},{\"type\":\"Text\",\"content\":{\"html\":\"<h2><u><em>BBBBBBBBB</em></u></h2>\"}},{\"type\":\"Text\",\"content\":{\"html\":\"<p>Viết hàm tính diện tích hình vuông</p>\"}},{\"type\":\"Code\",\"content\":{\"code\":\"function square(x :number):number {\\n    return x*x;\\n}\",\"isTest\":true,\"runable\":false,\"language\":\"typescript\",\"timeLimit\":1000,\"judgeContent\":{\"testCode\":\"class TestResult {\\n    succeeded : boolean;          \\n    reason : string;            \\n    input : string;             \\n    expected_output : string;   \\n    actual_output : string;  \\n    \\n    constructor(succeeded, reason, input, expected_output, actual_output) {\\n        this.succeeded = succeeded;\\n        this.reason = reason;\\n        this.input = input;\\n        this.expected_output = expected_output;\\n        this.actual_output = actual_output;\\n    }\\n}\\n\\nfunction executeTests() {\\n    let inputs = [0, 1, 2, 5];\\n    let expected_results = [0, 1, 4, 25];\\n    let results = [];\\n\\n    for(let i=0; i < inputs.length; i++) {\\n\\n        let output = square(inputs[i]);\\n        let succeeded = false;\\n        let reason = \\\"Incorrect Output!\\\";\\n\\n        if(output == expected_results[i]){\\n            succeeded = true;\\n            reason = \\\"Succeeded\\\";\\n        }\\n\\n        let result = new TestResult(succeeded, reason, String(inputs[i]), String(expected_results[i]), String(output));\\n        results.push(result);\\n    }\\n\\n    return results;\\n}\",\"executeCode\":\"function main() {\\n  let results = executeTests();\\n  let output = { test_results: results };\\n\\n  console.log(JSON.stringify(output));\\n}\\n\\nmain();\"},\"allowDownload\":false}},{\"type\":\"Text\",\"content\":{\"html\":\"<p>Viết chương trình tìm số lớn nhất trong mảng</p>\"}},{\"type\":\"Code\",\"content\":{\"code\":\"#include <iostream>\\n#include <vector>\\n#include <string>\\n\\nusing namespace std;\\n\\nint soLonNhat(vector<int> arr){\\n  \\n}\",\"isTest\":true,\"runable\":false,\"language\":\"c++\",\"timeLimit\":1000,\"judgeContent\":{\"testCode\":\"\\nstruct TestResult\\n{\\n  bool succeeded;\\n  std::string reason;\\n  std::string input;\\n  std::string expected_output;\\n  std::string actual_output;\\n  bool hidden;\\n};\\n\\nstd::vector<TestResult> executeTests()\\n{\\n  std::vector<std::vector<int>> inputs = {{3, 1, 4}, {3, 5, 7}, {512, 555}};\\n  std::vector<int> expected_outputs = {4, 7, 555};\\n  std::vector<bool> hide_test = {false, false, false};\\n  std::vector<TestResult> results;\\n\\n  for (int i = 0; i < inputs.size(); i++)\\n  {\\n    results.emplace_back(TestResult());\\n    auto result = &(results.back());\\n\\n    for (int j = 0; j < inputs[i].size(); j++)\\n    {\\n      result->input += std::to_string(inputs[i][j]);\\n      if (j != inputs[i].size() - 1)\\n      {\\n        result->input += \\\", \\\";\\n      }\\n    }\\n\\n    result->input = \\\"[\\\" + result->input + \\\"]\\\";\\n    result->expected_output = std::to_string(expected_outputs[i]);\\n\\n    auto actual_output = soLonNhat(inputs[i]);\\n    result->actual_output = std::to_string(actual_output);\\n    result->hidden = hide_test[i];\\n\\n    if (actual_output == expected_outputs[i])\\n    {\\n      result->reason = \\\"Succeeded\\\";\\n      result->succeeded = true;\\n    }\\n    else\\n    {\\n      result->reason = \\\"Incorrect Output\\\";\\n      result->succeeded = false;\\n    }\\n  }\\n\\n  return results;\\n}\",\"executeCode\":\"#include <iostream>\\n\\nint main() {\\n  std::vector<TestResult> results = executeTests();\\n\\n  if (results.size() == 0) {\\n    return 0;\\n  }\\n\\n  std::string output = \\\"{\\\\\\\"test_results\\\\\\\": [\\\";\\n\\n  int count = 0;\\n  for (const TestResult& result : results) {\\n    if (count > 0) {\\n      output += \\\",\\\";\\n    }\\n    output += \\\"{\\\";\\n    output += \\\"\\\\\\\"reason\\\\\\\": \\\\\\\"\\\" + result.reason + \\\"\\\\\\\",\\\";\\n    output += \\\"\\\\\\\"input\\\\\\\": \\\\\\\"\\\" + result.input + \\\"\\\\\\\",\\\";\\n    output += \\\"\\\\\\\"expected_output\\\\\\\": \\\\\\\"\\\" + result.expected_output + \\\"\\\\\\\",\\\";\\n    output += \\\"\\\\\\\"actual_output\\\\\\\": \\\\\\\"\\\" + result.actual_output + \\\"\\\\\\\",\\\";\\n\\n    std::string succeededStr = result.succeeded ? \\\"true\\\" : \\\"false\\\";\\n    std::string hidden = result.hidden? \\\"true\\\" : \\\"false\\\";\\n\\n    output += \\\"\\\\\\\"succeeded\\\\\\\": \\\" + succeededStr + \\\",\\\";\\n    output += \\\"\\\\\\\"hidden\\\\\\\": \\\" + hidden + \\\"}\\\";\\n\\n    count++;\\n  }\\n\\n\\n  output += \\\"]}\\\";\\n\\n  std::cout << output;\\n  return 0;\\n}\"},\"allowDownload\":false}}]","Hướng dẫn cách cài đặt NodeJS",978984540560502900]
query failed: INSERT INTO "lessons"("id", "created_at", "updated_at", "deleted_at", "title", "isCompleted", "order", "components", "summary", "course_category_id") VALUES ($1, DEFAULT, DEFAULT, DEFAULT, $2, DEFAULT, DEFAULT, $3, $4, $5) RETURNING "created_at", "updated_at", "isCompleted", "order", "summary" -- PARAMETERS: [589880434686375300,"Cách cài đặt môi trường NodeJS","[{\"type\":\"Text\",\"content\":{\"html\":\"<h2>Giới thiệu về NodeJS</h2>\"}},{\"type\":\"Text\",\"content\":{\"html\":\"<h2>NodeJS là một môi trường phát triển lập trình, dựa trên chrome V8 và các lib của C++</h2>\"}},{\"type\":\"Text\",\"content\":{\"html\":\"<h3>ccccccccccccc</h3>\"}},{\"type\":\"Text\",\"content\":{\"html\":\"<h2><u><em>BBBBBBBBB</em></u></h2>\"}},{\"type\":\"Text\",\"content\":{\"html\":\"<p>Viết hàm tính diện tích hình vuông</p>\"}},{\"type\":\"Code\",\"content\":{\"code\":\"function square(x :number):number {\\n    return x*x;\\n}\",\"isTest\":true,\"runable\":false,\"language\":\"typescript\",\"timeLimit\":1000,\"judgeContent\":{\"testCode\":\"class TestResult {\\n    succeeded : boolean;          \\n    reason : string;            \\n    input : string;             \\n    expected_output : string;   \\n    actual_output : string;  \\n    \\n    constructor(succeeded, reason, input, expected_output, actual_output) {\\n        this.succeeded = succeeded;\\n        this.reason = reason;\\n        this.input = input;\\n        this.expected_output = expected_output;\\n        this.actual_output = actual_output;\\n    }\\n}\\n\\nfunction executeTests() {\\n    let inputs = [0, 1, 2, 5];\\n    let expected_results = [0, 1, 4, 25];\\n    let results = [];\\n\\n    for(let i=0; i < inputs.length; i++) {\\n\\n        let output = square(inputs[i]);\\n        let succeeded = false;\\n        let reason = \\\"Incorrect Output!\\\";\\n\\n        if(output == expected_results[i]){\\n            succeeded = true;\\n            reason = \\\"Succeeded\\\";\\n        }\\n\\n        let result = new TestResult(succeeded, reason, String(inputs[i]), String(expected_results[i]), String(output));\\n        results.push(result);\\n    }\\n\\n    return results;\\n}\",\"executeCode\":\"function main() {\\n  let results = executeTests();\\n  let output = { test_results: results };\\n\\n  console.log(JSON.stringify(output));\\n}\\n\\nmain();\"},\"allowDownload\":false}},{\"type\":\"Text\",\"content\":{\"html\":\"<p>Viết chương trình tìm số lớn nhất trong mảng</p>\"}},{\"type\":\"Code\",\"content\":{\"code\":\"#include <iostream>\\n#include <vector>\\n#include <string>\\n\\nusing namespace std;\\n\\nint soLonNhat(vector<int> arr){\\n  \\n}\",\"isTest\":true,\"runable\":false,\"language\":\"c++\",\"timeLimit\":1000,\"judgeContent\":{\"testCode\":\"\\nstruct TestResult\\n{\\n  bool succeeded;\\n  std::string reason;\\n  std::string input;\\n  std::string expected_output;\\n  std::string actual_output;\\n  bool hidden;\\n};\\n\\nstd::vector<TestResult> executeTests()\\n{\\n  std::vector<std::vector<int>> inputs = {{3, 1, 4}, {3, 5, 7}, {512, 555}};\\n  std::vector<int> expected_outputs = {4, 7, 555};\\n  std::vector<bool> hide_test = {false, false, false};\\n  std::vector<TestResult> results;\\n\\n  for (int i = 0; i < inputs.size(); i++)\\n  {\\n    results.emplace_back(TestResult());\\n    auto result = &(results.back());\\n\\n    for (int j = 0; j < inputs[i].size(); j++)\\n    {\\n      result->input += std::to_string(inputs[i][j]);\\n      if (j != inputs[i].size() - 1)\\n      {\\n        result->input += \\\", \\\";\\n      }\\n    }\\n\\n    result->input = \\\"[\\\" + result->input + \\\"]\\\";\\n    result->expected_output = std::to_string(expected_outputs[i]);\\n\\n    auto actual_output = soLonNhat(inputs[i]);\\n    result->actual_output = std::to_string(actual_output);\\n    result->hidden = hide_test[i];\\n\\n    if (actual_output == expected_outputs[i])\\n    {\\n      result->reason = \\\"Succeeded\\\";\\n      result->succeeded = true;\\n    }\\n    else\\n    {\\n      result->reason = \\\"Incorrect Output\\\";\\n      result->succeeded = false;\\n    }\\n  }\\n\\n  return results;\\n}\",\"executeCode\":\"#include <iostream>\\n\\nint main() {\\n  std::vector<TestResult> results = executeTests();\\n\\n  if (results.size() == 0) {\\n    return 0;\\n  }\\n\\n  std::string output = \\\"{\\\\\\\"test_results\\\\\\\": [\\\";\\n\\n  int count = 0;\\n  for (const TestResult& result : results) {\\n    if (count > 0) {\\n      output += \\\",\\\";\\n    }\\n    output += \\\"{\\\";\\n    output += \\\"\\\\\\\"reason\\\\\\\": \\\\\\\"\\\" + result.reason + \\\"\\\\\\\",\\\";\\n    output += \\\"\\\\\\\"input\\\\\\\": \\\\\\\"\\\" + result.input + \\\"\\\\\\\",\\\";\\n    output += \\\"\\\\\\\"expected_output\\\\\\\": \\\\\\\"\\\" + result.expected_output + \\\"\\\\\\\",\\\";\\n    output += \\\"\\\\\\\"actual_output\\\\\\\": \\\\\\\"\\\" + result.actual_output + \\\"\\\\\\\",\\\";\\n\\n    std::string succeededStr = result.succeeded ? \\\"true\\\" : \\\"false\\\";\\n    std::string hidden = result.hidden? \\\"true\\\" : \\\"false\\\";\\n\\n    output += \\\"\\\\\\\"succeeded\\\\\\\": \\\" + succeededStr + \\\",\\\";\\n    output += \\\"\\\\\\\"hidden\\\\\\\": \\\" + hidden + \\\"}\\\";\\n\\n    count++;\\n  }\\n\\n\\n  output += \\\"]}\\\";\\n\\n  std::cout << output;\\n  return 0;\\n}\"},\"allowDownload\":false}}]","Hướng dẫn cách cài đặt NodeJS",978984540560502900]
error: error: duplicate key value violates unique constraint "PK_9b9a8d455cac672d262d7275730"
at Parser.parseErrorMessage (/app/node_modules/pg-protocol/src/parser.ts:369:69)
at Parser.handlePacket (/app/node_modules/pg-protocol/src/parser.ts:188:21)
at Parser.parse (/app/node_modules/pg-protocol/src/parser.ts:103:30)
at TLSSocket.<anonymous> (/app/node_modules/pg-protocol/src/index.ts:7:48)
at TLSSocket.emit (node:events:513:28)
at addChunk (node:internal/streams/readable:324:12)
at readableAddChunk (node:internal/streams/readable:297:9)
at TLSSocket.Readable.push (node:internal/streams/readable:234:10)
at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23) {
length: 239,
severity: 'ERROR',
code: '23505',
detail: 'Key (id)=(589880434686375300) already exists.',
hint: undefined,
position: undefined,
internalPosition: undefined,
internalQuery: undefined,
where: undefined,
schema: 'public',
table: 'lessons',
column: undefined,
dataType: undefined,
constraint: 'PK_9b9a8d455cac672d262d7275730',
file: 'nbtinsert.c',
line: '664',
routine: '_bt_check_unique'
}
query: ROLLBACK

**Comment by mnguyen081002** [comment]
curl 'https://codesmooth-api-production.up.railway.app/api/admin/lesson' \
  -H 'authority: codesmooth-api-production.up.railway.app' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: en-US,en;q=0.9,vi;q=0.8' \
  -H 'content-type: application/json' \
  -H 'dnt: 1' \
  -H 'origin: https://codesmooth.netlify.app' \
  -H 'referer: https://codesmooth.netlify.app/' \
  -H 'sec-ch-ua: "Google Chrome";v="113", "Chromium";v="113", "Not-A.Brand";v="24"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: cross-site' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36' \
  --data-raw $'{"id":589880434686375300,"title":"Cách cài đặt môi trường NodeJS","summary":"Hướng dẫn cách cài đặt NodeJS","components":[{"type":"Text","content":{"html":"<h2>Giới thiệu về NodeJS</h2>"}},{"type":"Text","content":{"html":"<h2>NodeJS là một môi trường phát triển lập trình, dựa trên chrome V8 và các lib của C++</h2>"}},{"type":"Text","content":{"html":"<h3>ccccccccccccc</h3>"}},{"type":"Text","content":{"html":"<h2><u><em>BBBBBBBBB</em></u></h2>"}},{"type":"Text","content":{"html":"<p>Viết hàm tính diện tích hình vuông</p>"}},{"type":"Code","content":{"code":"function square(x :number):number {\\n    return x*x;\\n}","isTest":true,"runable":false,"language":"typescript","timeLimit":1000,"judgeContent":{"testCode":"class TestResult {\\n    succeeded : boolean;          \\n    reason : string;            \\n    input : string;             \\n    expected_output : string;   \\n    actual_output : string;  \\n    \\n    constructor(succeeded, reason, input, expected_output, actual_output) {\\n        this.succeeded = succeeded;\\n        this.reason = reason;\\n        this.input = input;\\n        this.expected_output = expected_output;\\n        this.actual_output = actual_output;\\n    }\\n}\\n\\nfunction executeTests() {\\n    let inputs = [0, 1, 2, 5];\\n    let expected_results = [0, 1, 4, 25];\\n    let results = [];\\n\\n    for(let i=0; i < inputs.length; i++) {\\n\\n        let output = square(inputs[i]);\\n        let succeeded = false;\\n        let reason = \\"Incorrect Output\u0021\\";\\n\\n        if(output == expected_results[i]){\\n            succeeded = true;\\n            reason = \\"Succeeded\\";\\n        }\\n\\n        let result = new TestResult(succeeded, reason, String(inputs[i]), String(expected_results[i]), String(output));\\n        results.push(result);\\n    }\\n\\n    return results;\\n}","executeCode":"function main() {\\n  let results = executeTests();\\n  let output = { test_results: results };\\n\\n  console.log(JSON.stringify(output));\\n}\\n\\nmain();"},"allowDownload":false}},{"type":"Text","content":{"html":"<p>Viết chương trình tìm số lớn nhất trong mảng</p>"}},{"type":"Code","content":{"code":"#include <iostream>\\n#include <vector>\\n#include <string>\\n\\nusing namespace std;\\n\\nint soLonNhat(vector<int> arr){\\n  \\n}","isTest":true,"runable":false,"language":"c++","timeLimit":1000,"judgeContent":{"testCode":"\\nstruct TestResult\\n{\\n  bool succeeded;\\n  std::string reason;\\n  std::string input;\\n  std::string expected_output;\\n  std::string actual_output;\\n  bool hidden;\\n};\\n\\nstd::vector<TestResult> executeTests()\\n{\\n  std::vector<std::vector<int>> inputs = {{3, 1, 4}, {3, 5, 7}, {512, 555}};\\n  std::vector<int> expected_outputs = {4, 7, 555};\\n  std::vector<bool> hide_test = {false, false, false};\\n  std::vector<TestResult> results;\\n\\n  for (int i = 0; i < inputs.size(); i++)\\n  {\\n    results.emplace_back(TestResult());\\n    auto result = &(results.back());\\n\\n    for (int j = 0; j < inputs[i].size(); j++)\\n    {\\n      result->input += std::to_string(inputs[i][j]);\\n      if (j \u0021= inputs[i].size() - 1)\\n      {\\n        result->input += \\", \\";\\n      }\\n    }\\n\\n    result->input = \\"[\\" + result->input + \\"]\\";\\n    result->expected_output = std::to_string(expected_outputs[i]);\\n\\n    auto actual_output = soLonNhat(inputs[i]);\\n    result->actual_output = std::to_string(actual_output);\\n    result->hidden = hide_test[i];\\n\\n    if (actual_output == expected_outputs[i])\\n    {\\n      result->reason = \\"Succeeded\\";\\n      result->succeeded = true;\\n    }\\n    else\\n    {\\n      result->reason = \\"Incorrect Output\\";\\n      result->succeeded = false;\\n    }\\n  }\\n\\n  return results;\\n}","executeCode":"#include <iostream>\\n\\nint main() {\\n  std::vector<TestResult> results = executeTests();\\n\\n  if (results.size() == 0) {\\n    return 0;\\n  }\\n\\n  std::string output = \\"{\\\\\\"test_results\\\\\\": [\\";\\n\\n  int count = 0;\\n  for (const TestResult& result : results) {\\n    if (count > 0) {\\n      output += \\",\\";\\n    }\\n    output += \\"{\\";\\n    output += \\"\\\\\\"reason\\\\\\": \\\\\\"\\" + result.reason + \\"\\\\\\",\\";\\n    output += \\"\\\\\\"input\\\\\\": \\\\\\"\\" + result.input + \\"\\\\\\",\\";\\n    output += \\"\\\\\\"expected_output\\\\\\": \\\\\\"\\" + result.expected_output + \\"\\\\\\",\\";\\n    output += \\"\\\\\\"actual_output\\\\\\": \\\\\\"\\" + result.actual_output + \\"\\\\\\",\\";\\n\\n    std::string succeededStr = result.succeeded ? \\"true\\" : \\"false\\";\\n    std::string hidden = result.hidden? \\"true\\" : \\"false\\";\\n\\n    output += \\"\\\\\\"succeeded\\\\\\": \\" + succeededStr + \\",\\";\\n    output += \\"\\\\\\"hidden\\\\\\": \\" + hidden + \\"}\\";\\n\\n    count++;\\n  }\\n\\n\\n  output += \\"]}\\";\\n\\n  std::cout << output;\\n  return 0;\\n}"},"allowDownload":false}}],"course_category_id":978984540560502900}' \
  --compressed
